### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by neodon** [nenoNaninu/TypedSignalR.Client.DevTools#23]
Hello. I discovered your projects today and they are awesome. You've solved several challenges I was facing with SignalR and TypeScript such as debugging and type generation. I hope you are able to see more people using them soon.

Are you open to contributions? If so, what are some things you would like to see in this project?

**Comment by nenoNaninu** [comment]
Thanks, I hope my project will help you in your development:)

Contributions are welcome in any way! I am always open to issues (bug reports, feature requests, etc.) and pull requests (bug fixes, feature additions, etc.). Also, there are many ways to contribute, such as writing a blog to show how to use it or publishing an example repository. Of course, any other contribution is OK if you do not violate a project license!
