### ISSUE TITLE
Use DevTools and GenerateClient, SourceGenerate create two UseSignalRHubSpecification

### ISSUE THREAD

**Issue by magals** [nenoNaninu/TypedSignalR.Client.DevTools#31]
i want to use your two projects:
TypedSignalR.Client.DevTools
TypedSignalR.Client

and of course I have two projects, server and shared.
shared includes the following libraries:
TypedSignalR.Client.DevTools" Version="1.1.2"
TypedSignalR.Client" Version="3.4.0"

and the problem is that the generated method "UseSignalRHubSpecification" appeared in two projects at once, and when you try to connect this method to the server, this method causes an error:

Error CS0121 The call is ambiguous between the following methods or properties: 'TypedSignalR.Client.DevTools.EndpointRouteBuilderExtensions.UseSignalRHubSpecification(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder)' and 'TypedSignalR.Client.DevTools.EndpointRouteBuilderExtensions.UseSignalRH ubSpecification(Microsoft.AspNetCore.Routing .IEndpointRouteBuilder)' SignalR.GenerationClientAndDevTools.Server

Is there a way to get around this problem?

![Screenshot 2023-08-08 180315](https://github.com/nenoNaninu/TypedSignalR.Client.DevTools/assets/15940153/cac22b13-565c-4354-b464-0272d778c033)

**Comment by nenoNaninu** [comment]
Thanks for the report. I released the version that solves this problem. Please try to upgrade the version of `TypedSignalR.Client.DevTools` to `v1.2.0`.
