### ISSUE TITLE
Hub methods are not displayed if use a variable for the path

### ISSUE THREAD

**Issue by magals** [nenoNaninu/TypedSignalR.Client.DevTools#45]
Thank you for the tool, it is truly wonderful.
But, after I described my hub, and would like to wrap it in a separate extension method for asp.net, I discovered that if I use a variable as a path, then the hub methods are not displayed on the site.

Is this some kind of bug or am I missing something?

![image](https://github.com/nenoNaninu/TypedSignalR.Client.DevTools/assets/15940153/c2fd8fd5-c824-409d-9be9-e746264527de)
![image](https://github.com/nenoNaninu/TypedSignalR.Client.DevTools/assets/15940153/6b9d7475-e857-4523-bcff-d3682cf6b057)

**Comment by magals** [comment]
there is also a problem when a hub is added using the extension method
![image](https://github.com/nenoNaninu/TypedSignalR.Client.DevTools/assets/15940153/0d1b4d03-27bc-4357-b7e4-13c6ea8cfaad)

**Comment by nenoNaninu** [comment]
See [README](https://github.com/nenoNaninu/TypedSignalR.Client.DevTools#usage).

>Finally, add MapHub as usual in Program.cs. Note that the first argument of MapHub must be a string literal because this library determines the hub URL at compile time.

It can also be used within extension methods without any problems. Check if the `[Hub]` and `[Receiver]` attributes are applied to the interface.

```cs
// Program.cs
// It works fine.

app.MapControllers();

app.AddChatHub();

app.Run();

public static class Extensions
{
    public static void AddChatHub(this IEndpointRouteBuilder endpoints)
    {
        endpoints.MapHub<ChatHub>("/hubs/ChatHub");
    }
}

**Comment by magals** [comment]
> Смотрите [README.](https://github.com/nenoNaninu/TypedSignalR.Client.DevTools#usage)

>
const string DefaultPath = "/_basehub"; - shouldn't it work?
this string literal is already known at the time of compilation, but the hubs are still not visible

> public static class Extensions
{
    public static void MapChatHub(this IEndpointRouteBuilder endpoints)
    {
        endpoints.MapHub<ChatHub>("/hubs/ChatHub");
    }
}

this only works if this extension is located in the server project; if I push it into the Share library project, then Hubs are not displayed

**Comment by nenoNaninu** [comment]
>const string DefaultPath = "/_basehub"; - shouldn't it work?
this string literal is already known at the time of compilation, but the hubs are still not visible

Currently, it must be a string literal, not a const string.

>this only works if this extension is located in the server project; if I push it into the Share library project, then Hubs are not displayed

That's a specification. This library, like most source generators, only analyzes code in a project. Analyzing reference projects is expensive.

**Comment by nenoNaninu** [comment]
Support const string as a parameter for `MapHub` from v1.2.1.
