### ISSUE TITLE
Register multiple interfaces

### ISSUE THREAD

**Issue by ISmellYu** [nenoNaninu/TypedSignalR.Client.DevTools#55]
Hi,
When trying to inherit from some base interface it doesnt register it.
Aside from that, very usefull tool :)

IBaseHub
```C#
[Hub]
public interface IBaseHub
{
	public Task<bool> Hello();
}
```

IChatHub
```C#
[Hub]
public interface IChatHub : IBaseHub
{
	
}
```

ChatHub
```C#
[SignalRHub]
public class ChatHub : Hub<IChatReceiver>, IChatHub
{
	public Task<bool> Hello()
	{
		return Task.FromResult(true);
	}
}
```

Result:
![image](https://github.com/nenoNaninu/TypedSignalR.Client.DevTools/assets/38290598/30fc7492-ef1f-4afd-8c6e-9839089bae90)

**Comment by nenoNaninu** [comment]
Thank you for reporting your issue. I will support it in the next release.

**Comment by nenoNaninu** [comment]
This issue was resolved in v1.2.3. Please try it!

**Comment by ISmellYu** [comment]
Working, thanks for quickly resolving my issue :)

**Comment by ISmellYu** [comment]
Working, thanks for quickly resolving my issue :)
